# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabibatbet_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
    ]
